In [ ]:
#1. What is a Python library? Why ^o we use Python libraries?

'''Python libraries are used to create applications and models in variety of fields.
by using libraries we can manipulate data, we can show the data in visualisation
format and by using numpy we can perform mathematical operations also.''

In [ ]:
#2. What is the ^ifference between Numpy array an^ List?

'''Numpy arrays have homogeneous data type,make more compact memory efficient than list ,list 
contains heterogeneous data that means contains different data types.
Fixed Data Type: NumPy arrays have a fixed data type, reducing memory overhead by eliminating 
the need to store type information for each element.'''

In [10]:
#3. Fin^ the shape, size an^ ^imension of the following array?
#given array
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
#importing numpy module as np
import numpy as np
#finding size by using size attribute
print("Size of given array is: ")
np.size(arr)

Size of given array is: 


12

In [9]:
#finding shape using shape attribute
print("Shape of given array is: ")
np.shape(arr)

Shape of given array is: 


(3, 4)

In [8]:
#finding dimension using ndim
print("Dimension of given array is: ")
np.ndim(arr)

Dimension of given array is: 


2

In [3]:
'''4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
#importing 
import numpy as np
#given array
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
#using index method like list to get first row
#store that in x
x = arr[0]
#printing x
print(x)

[1, 2, 3, 4]


In [8]:
'''5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
#importing 
import numpy as np
#given array
arr = [[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]
Mat = print(np.mat(arr))
#using index method like list to get third  row anf fourth coloumn
#store that in x
x = arr[2]
#printing x
print("Third row in given matrix is: ",x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Third row in given matrix is:  [9, 10, 11, 12]


In [17]:
#getting fourth column using numpy and slicing 
np.array(arr)[:,3]

array([ 4,  8, 12])

In [29]:
#15. What is broa^casting in Numpy?
'''The term broadcasting refers to how NumPy treats arrays with different dimensions during arithmetic operations which lead to certain constraints,
the smaller array is broadcast across the larger array so that they have compatible shapes'''
import numpy as np

a = np.array([5, 7, 3, 1])
b = np.array([90, 50, 0, 30])

# array are compatible because of same Dimension
c = a * b
print(c)

[450 350   0  30]


In [30]:
import numpy as np
A = np.array([[11, 22, 33], [10, 20, 30]])
print(A)

b = 4
print(b)

C = A + b
print(C)

[[11 22 33]
 [10 20 30]]
4
[[15 26 37]
 [14 24 34]]


In [32]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^?
'''reshape() function is used to create a new array of the same size (as the original array)
but of different desired dimensions.
It uses to convert 1d to nd.'''
#importing numpy module as np
import numpy as np
#creating array using arrange function 
arr = np.arange(6)

In [33]:
arr

array([0, 1, 2, 3, 4, 5])

In [35]:
#using reshape converting array to new array with different dimension
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [43]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
'''numpy.ndarray.byteswap() function toggle between low-endian and big-endian data
representation by returning a byteswapped array, optionally swapped in-place.
Syntax: ndarray.byteswap(inplace=False)'''

# byteswap() function 
import numpy as np

# a is an array of integers. 
a = np.array([1, 256, 100],dtype = np.int16)

print(a.byteswap(True)) 


[  256     1 25600]


In [39]:
x = np.array([1, 256, 100])
x.dtype

dtype('int64')

In [50]:
'''11. Consi^er the following matrix'''
#importing numpy module as np
import numpy as np
MatrixA = [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]
MatrixB =  [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]
#addition
np.add(MatrixA,MatrixB)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [53]:
#subtraction
np.subtract(MatrixA,MatrixB)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
#division
np.divide(MatrixA,MatrixB)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
#index multiplication using numpy
np.multiply(MatrixA,MatrixB)

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [57]:
np.dot(MatrixA,MatrixB)
#dot product is possibe in matrix only if no.of coloumns in first matrix
#equals to no.of rows in second matricx

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [59]:
'''10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
#importing numpy module as np
import numpy as np
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
print(arr)
np.transpose(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [62]:
'''9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]'''
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [63]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
np.random.rand(2,6)
'''The numpy.random.rand() function creates an array of specified shapes 
fills it with random values and generates random numbers with Numpy'''

array([[0.78476143, 0.076996  , 0.43083358, 0.70982678, 0.4474576 ,
        0.63216784],
       [0.28728363, 0.08453223, 0.9803063 , 0.91253986, 0.29261766,
        0.72499176]])

In [64]:
np.random.randn(2,6)
'''NumPy random. randn() function in Python is used to return random values
from the normal distribution in a specified shape.'''

array([[-1.22035461,  0.27760906, -0.09771579, -0.31305135,  0.49150506,
        -0.0827044 ],
       [-0.01130475,  0.50550431, -0.21310942,  1.06947151,  2.18998455,
         0.91154906]])

In [65]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
#using random.randint to generate random numbers
x = np.random.randint(0,1, (3,3))

In [66]:
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])